version: '3'

services:

  postgres:
    image: 'postgres:14.2'
    ports: 
      - "5433:5432" # first is the local machine port, second is the container port
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/ # to persist data the db-data/posgres folder is mounted to the container's /var/lib/postgresql/data/ folder
